function Exp3FMRunAllreva = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  EXP3FMRUNALLREVA = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  EXP3FMRUNALLREVA = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  EXP3FMRUNALLREVA = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Exp3FMRunAllreva = importfile("C:\Users\jtmil\OneDrive\Desktop\Cal Poly Pomona\CPP GIT\ARO 4351L - Wind Tunnel Lab\Exp #3\Exp 3 FM Run All rev a.xlsx", "Exp 3 FM Run All rev a", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Mar-2024 12:41:22

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 22);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Test", "Run", "Point", "TestType", "PitchAbs", "YawAbs", "PitchUser", "YawUser", "RollUser", "AvgSize", "NF", "PM", "SF", "YM", "RM", "AF", "VelFs", "Vel_SIMs", "PinfPsi", "Pinf_SIKPa", "Temp_SIC", "Mach"];
opts.VariableTypes = ["double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "TestType", "EmptyFieldRule", "auto");

% Import the data
Exp3FMRunAllreva = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Exp3FMRunAllreva = [Exp3FMRunAllreva; tb]; %#ok<AGROW>
end

end